version: "3"

services:
    php:
        build:
            context: .
        volumes:
            -   ./:/var/www/html
        depends_on:
            -   db
            -   redis

    web:
        image: nginx:latest
        working_dir: /var/www/html
        volumes:
            -   ./:/var/www/html
            - .docker/nginx/nginx_template_local.conf:/etc/nginx/conf.d/default.conf
        ports:
            -   "8080:80"
        depends_on:
            -   db
            -   redis
    db:
        image: mysql:latest
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
        volumes:
            -   mysqldata:/var/lib/mysql
    redis:
        image: redis:latest
        volumes:
            -   redisdata:/data
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            -   "8000:80"
volumes:
    mysqldata: ~
    redisdata: ~
